name: CI Pipeline

on:
  push:
    branches:
      - Testing
      - Michelle_branch
      - Paco_branch
      - Checha_branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: List files in current directory
        run: ls

      - name: Change to frontend directory
        run: cd frontend

      - name: List files in frontend directory
        run: ls

      - name: Install dependencies
        run: npm install --force
        
      -name: dependencies Babel
        run: npm install --save-dev @babel/preset-react --force

      - name: Run tests in frontend
        run: npm test
